export const CHANGE_USER_LOCATION = 'user/CHANGE_USER_LOCATION'
export const CHANGE_CUR_LOCATION = 'user/CHANGE_CUR_LOCATION'
export const CHANGE_UPDATE_VISIABLE = 'user/CHANGE_UPDATE_VISIABLE'
export const CHANGE_PASSWORD_VISIABLE = 'user/CHANGE_PASSWORD_VISIABLE'